### ISSUE TITLE
Disclaimer text not displayed in Relativity 10+

### ISSUE THREAD

**Issue by KaNaPaPi** [relativitydev/disclaimer-acceptance-log#1]
Disclaimer text is not displayed in Relativity 10.0 or higher.

**Comment by MsmithKcura** [comment]
It is also possible that the html/css used to display the disclaimer is no longer supported causing it to be rendered differently. In this case the HTML stored in the DLLs would need to be updated. The HTML/CSS is stored as "LoginPage" in KCD_1042192.Utility/HTML.resx. It is updated in the solution on Relativity whenever the main disclaimer config is updated.

I recommend logging into relativity and forcing the broken disclaimer to display.  Grab the current HTML used to display the disclaimer from [EDDS].[eddsdbo].[Disclaimer]. Paste it into an HTML editor and update so that it is displayed correctly. Save the updated HTML back into [EDDS].[eddsdbo].[Disclaimer], refresh the page and verify that the Disclaimer displays correctly. After it's perfect, update "LoginPage" in KCD_1042192.Utility/HTML.resx with the new code, rebuild the Dlls, update them on Relativity and Lastly please share your update with the community.

Please note that you'll have to enable/disable the solution from the main disclaimer config in order to see changes from the updated DLLs propagate.

**Comment by mrobustelli** [comment]
@KaNaPaPi Is this what you are seeing?  I see the page, but not the text it is supposed to display.  I'm gonna try and follow Marlon's advice here.  This may be connected to Issue #2 
![image](https://user-images.githubusercontent.com/23082548/52376318-6817eb80-2a27-11e9-82c0-e206ff6818fa.png)

**Comment by mrobustelli** [comment]
Based on my initial assessment, It feels like @MsmithKcura is right on, just going to have to figure out the HTML.  It could be time consuming. I will try based on my availability.   If someone else gets it first, please let me know.

**Comment by mrobustelli** [comment]
So if I edit the Eddsdbo.Disclaimer table in edds and just put in FOOBAR. That shows up and the mouse works.  This leads me to believe it is the HTML issue.  Now it is just a matter of finding the right HTML and script.  @KaNaPaPi What does "Timely Manner" mean in terms of urgency?  Tonight? Tomorrow? Early Next week?

**Comment by mrobustelli** [comment]
When I clear Message in the Disclaimer table and only add FOOBAR, that displays and the mouse works.
![image](https://user-images.githubusercontent.com/23082548/52382954-f9de2380-2a3c-11e9-9548-c24e95cf2845.png)

When I add the div to the message the loading div overlays everything (so far so good) The button does not click because the overlay is over it.
![image](https://user-images.githubusercontent.com/23082548/52382932-de731880-2a3c-11e9-9418-9a7515415418.png)
![image](https://user-images.githubusercontent.com/23082548/52383014-390c7480-2a3d-11e9-939a-c16565401c7d.png)

When I try to add simple script, like the onload...I get an error

![image](https://user-images.githubusercontent.com/23082548/52383062-62c59b80-2a3d-11e9-8a56-bb4bd1d5f70d.png)
![image](https://user-images.githubusercontent.com/23082548/52383098-8557b480-2a3d-11e9-920a-f2449c4e2fb9.png)

I definitely think there is some Javascript and HTML wizardry that needs to take place here.

If I get time later tonight I will continue to dig, if not and time opens up tomorrow I will check it out as well.

sorry for the pics of code instead of text, but Github would not display the html in the code tags.

**Comment by mrobustelli** [comment]
Crap, answered part of my own problem.  Looks like load was deprecated in jquery 3 something.  Need to change window.load to window.on.   Don't know if this fixed the whole problem yet but closing in. 

Now need to figure out why message is not being displayed and agreement not being recorded in DB.  I suspect more Javascript fun.

**Comment by KaNaPaPi** [comment]
Mark, timely manner is a week or two. Thanks for your help!

**Comment by mrobustelli** [comment]
@KaNaPaPi I found the fix!...it is the window onload...

I changed 
`$(window).load(function() {`

to
`$(window).on("load", function() {`

and it worked and recorded the agreement.

I will not likely have time to apply it to the repo and post.  If any of this is confusing, I might have a little time tomorrow to walk you through it.  It would be awesome if you would be willing to post the fix back.

**Comment by KaNaPaPi** [comment]
I will give this a shot in the morning.  I will definitely get this pushed.

**Comment by mrobustelli** [comment]
Sweet,  after further though, instead of having to maintain 2 different versions of the source code for this fix, we can probably do something like get the jQuery version using `var version = $.fn.jquery` and then do something like `if (version > 3) {$(window).on("load")..} else {$(window).load(function() {....`

Then we can use all the same code base for different versions.

**Comment by KaNaPaPi** [comment]
I have changed the data in the HTML.resx file.  I have re-deployed the custom page, as well as the KCD_1042192.Utility.dll.  I am still getting $(window).load(function() {.  The change is not being affected.  Maybe I'll try in a different environment to see if it's an environmental issue.

**Comment by MsmithKcura** [comment]
Make sure to toggle the solution via the main config object afterwards the changes should propagate.

Afterwards verify that the change propagated by examining the HTML in [EDDS].[eddsdbo].[Disclaimer]. It might be a browser cache issue if the DB is updated but the Disclaimer continues to be displayed with the old code.

**Comment by KaNaPaPi** [comment]
Thanks for holding my hand gentlemen.  I have the application working in 10.0.X.X.  Going to send this to our QA team now.

**Comment by mrobustelli** [comment]
@KaNaPaPi, just wanted to check in.  See if all is right with the world and if you may have some time, or need some help in submitting the pull request.   Just let me know.

**Comment by KaNaPaPi** [comment]
Yes, I have absolutely no idea how to publish my code back to GitHub.
